name = str("Fatolu Emmanuella")
Internid = str('HNG-02017')
email =str('fatoluemmanuella@gmail.com')
language = str('Python')
print('Hello World, this is ' + name  + ' with HNGi7 ID ' + Internid + ' and email ' + email + ' using ' + language + ' for stage 2 task')