# This is a basic workflow to help you get started with Actions

name: MergeApprovedPR

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: submissions
      - name: merge
        uses: framer/merge-approved-pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABEL: ready
